### ISSUE TITLE
Fresh install: fails to find 'bindings' file

### ISSUE THREAD

**Issue by leegee** [smollweide/node-mock-server#131]
Please see below:
```
PS C:\Users\LGoddard\src\project\vanilla>  npm install node-mock-server --save-dev
+ node-mock-server@0.25.0
added 59 packages from 51 contributors in 10.305s
PS C:\Users\LGoddard\src\project\vanilla>
PS C:\Users\LGoddard\src\project\vanilla>
PS C:\Users\LGoddard\src\project\vanilla>
PS C:\Users\LGoddard\src\project\vanilla>  node node_modules/node-mock-server/init

 |                                    |
 |        node-mock-server init       |
 |                                    |

? Enter the desired path (from your current directory) to store the mock server data fixtures
➜ Wrote directory "fixtures"
➜ Wrore directory "fixtures\rest"
➜ .gitignore was updated
? Do you want to use the default configuration? Yes
➜ Wrote file "fixtures/index.js"

Run `node fixtures` for starting the server!
PS C:\Users\LGoddard\src\project\vanilla> node fixtures
C:\Users\LGoddard\src\project\vanilla\node_modules\bindings\bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\LGoddard\src\project\vanilla\node_modules\deasync\build\deasync.node
 → C:\Users\LGoddard\src\project\vanilla\node_modules\deasync\build\Debug\deasync.node
 → C:\Users\LGoddard\src\project\vanilla\node_modules\deasync\build\Release\deasync.node
 → C:\Users\LGoddard\src\project\vanilla\node_modules\deasync\out\Debug\deasync.node
 → C:\Users\LGoddard\src\project\vanilla\node_modules\deasync\Debug\deasync.node
 → C:\Users\LGoddard\src\project\vanilla\node_modules\deasync\out\Release\deasync.node
 → C:\Users\LGoddard\src\project\vanilla\node_modules\deasync\Release\deasync.node
 → C:\Users\LGoddard\src\project\vanilla\node_modules\deasync\build\default\deasync.node
 → C:\Users\LGoddard\src\project\vanilla\node_modules\deasync\compiled\12.12.0\win32\x64\deasync.node
    at bindings (C:\Users\LGoddard\src\project\vanilla\node_modules\bindings\bindings.js:88:9)
    at C:\Users\LGoddard\src\project\vanilla\node_modules\deasync\index.js:34:32
    at Object.<anonymous> (C:\Users\LGoddard\src\project\vanilla\node_modules\deasync\index.js:76:2)
    at Module._compile (internal/modules/cjs/loader.js:956:30)        
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)  
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at Object.<anonymous> (C:\Users\LGoddard\src\project\vanilla\node_  tries: [
    'C:\\Users\\LGoddard\\src\\project\\vanilla\\node_modules\\deasync\\build\\deasync.node',
    'C:\\Users\\LGoddard\\src\\project\\vanilla\\node_modules\\deasync\\build\\Debug\\deasync.node',
    'C:\\Users\\LGoddard\\src\\project\\vanilla\\node_modules\\deasync\\build\\Release\\deasync.node',
    'C:\\Users\\LGoddard\\src\\project\\vanilla\\node_modules\\deasync\\out\\Debug\\deasync.node',
    'C:\\Users\\LGoddard\\src\\project\\vanilla\\node_modules\\deasync\\Debug\\deasync.node',
    'C:\\Users\\LGoddard\\src\\project\\vanilla\\node_modules\\deasync\\out\\Release\\deasync.node',
    'C:\\Users\\LGoddard\\src\\project\\vanilla\\node_modules\\deasync\\Release\\deasync.node',
    'C:\\Users\\LGoddard\\src\\project\\vanilla\\node_modules\\deasync\\build\\default\\deasync.node',
    'C:\\Users\\LGoddard\\src\\project\\vanilla\\node_modules\\deasync\\compiled\\12.12.0\\win32\\x64\\deasync.node'
  ]
}
PS C:\Users\LGoddard\src\project\vanilla> node --version
v12.12.0
PS C:\Users\LGoddard\src\project\vanilla>
```

**Comment by leegee** [comment]
Cf https://github.com/nodejs/node-gyp/issues/1511

**Comment by leegee** [comment]
As in the linked issue, removing `node_modules` and reinstalling everything removed the problem.
