### ISSUE TITLE
Can't run the server over SSL/TLS: Self-signed certificate not loaded

### ISSUE THREAD

**Issue by rashmasch** [smollweide/node-mock-server#95]
Hi @smollweide, while using the mock server within a project that encrypts HTTP traffic (SSL, TLS) we found an issue with the self-signed SSL certificate. After creating one with openssl terminal utility, we are not able to run the server.

Here is my local setup:
node  8.9.2
npm  5.6.0
mock server 0.22.0

And configuration of the server:
```
var mockServer = require('node-mock-server');
var path = require('path');

mockServer({
    'restPath': path.join(__dirname, '/rest'),
    'uiPath': '/',
    'title': 'JSON Mock Server',
    'version': 1,
    'urlBase': 'https://test.local:3001',
    'urlPath': '/rest/v1',
    'port': 3001,
    'certificate': path.join(__dirname, '/test.crt'),
    'privateKey': path.join(__dirname, '/test.key'),
    'contentType': 'application/json',
    'accessControlExposeHeaders': 'X-Total-Count',
    'accessControlAllowOrigin': '*',
    'accessControlAllowMethods': 'GET, POST, PUT, OPTIONS, DELETE, PATCH, HEAD',
    'accessControlAllowHeaders': 'origin, x-requested-with, content-type',
    'accessControlAllowCredentials': 'true',
    'headers': {},
    'open': true,
    'dirName': __dirname
});
```

Error trace:
```
> node run-mock-server.js

_tls_common.js:88
      c.context.setCert(options.cert);
                ^
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:88:17)
    at Server (_tls_wrap.js:803:25)
    at new Server (https.js:54:14)
    at Object.createServer (https.js:76:10)
    at AppController.init(...)
    ...
```

It looks like some dependency issue, did you experience a similar problem?
Thanks.

**Comment by smollweide** [comment]
Hi @rashmasch,
the problem is that `options.certificate` and `options.privateKey` expect an fileData not an path.
Because the init script generates it wrongly I fixed it by allowing path or fileData.
`npm i -D node-mock-server@0.22.1`
